/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.stable.core.database.schema.neon_data.tables


import com.islandstudio.neon.stable.core.database.schema.neon_data.NeonData
import com.islandstudio.neon.stable.core.database.schema.neon_data.keys.FK_DT_PLAYER_PROFILE_DT_ROLE_ROLE_ID
import com.islandstudio.neon.stable.core.database.schema.neon_data.keys.PK_DT_PLAYER_PROFILE
import com.islandstudio.neon.stable.core.database.schema.neon_data.keys.UQ_DT_PLAYER_PROFILE_PLAYER_NAME
import com.islandstudio.neon.stable.core.database.schema.neon_data.tables.DtRole.DtRolePath
import com.islandstudio.neon.stable.core.database.schema.neon_data.tables.records.DtPlayerProfileRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime
import java.util.*


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DtPlayerProfile(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DtPlayerProfileRecord>?,
    parentPath: InverseForeignKey<out Record, DtPlayerProfileRecord>?,
    aliased: Table<DtPlayerProfileRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DtPlayerProfileRecord>(
    alias,
    NeonData.NEON_DATA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>NEON_DATA.DT_PLAYER_PROFILE</code>
         */
        val DT_PLAYER_PROFILE: DtPlayerProfile = DtPlayerProfile()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DtPlayerProfileRecord> = DtPlayerProfileRecord::class.java

    /**
     * The column <code>NEON_DATA.DT_PLAYER_PROFILE.PLAYER_UUID</code>.
     */
    val PLAYER_UUID: TableField<DtPlayerProfileRecord, UUID?> = createField(DSL.name("PLAYER_UUID"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>NEON_DATA.DT_PLAYER_PROFILE.PLAYER_NAME</code>.
     */
    val PLAYER_NAME: TableField<DtPlayerProfileRecord, String?> = createField(DSL.name("PLAYER_NAME"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>NEON_DATA.DT_PLAYER_PROFILE.JOIN_AT</code>.
     */
    val JOIN_AT: TableField<DtPlayerProfileRecord, LocalDateTime?> = createField(DSL.name("JOIN_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>NEON_DATA.DT_PLAYER_PROFILE.ROLE_ID</code>.
     */
    val ROLE_ID: TableField<DtPlayerProfileRecord, Long?> = createField(DSL.name("ROLE_ID"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<DtPlayerProfileRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DtPlayerProfileRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DtPlayerProfileRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>NEON_DATA.DT_PLAYER_PROFILE</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>NEON_DATA.DT_PLAYER_PROFILE</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>NEON_DATA.DT_PLAYER_PROFILE</code> table reference
     */
    constructor(): this(DSL.name("DT_PLAYER_PROFILE"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DtPlayerProfileRecord>?, parentPath: InverseForeignKey<out Record, DtPlayerProfileRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, DT_PLAYER_PROFILE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class DtPlayerProfilePath : DtPlayerProfile, Path<DtPlayerProfileRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DtPlayerProfileRecord>?, parentPath: InverseForeignKey<out Record, DtPlayerProfileRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<DtPlayerProfileRecord>): super(alias, aliased)
        override fun `as`(alias: String): DtPlayerProfilePath = DtPlayerProfilePath(DSL.name(alias), this)
        override fun `as`(alias: Name): DtPlayerProfilePath = DtPlayerProfilePath(alias, this)
        override fun `as`(alias: Table<*>): DtPlayerProfilePath = DtPlayerProfilePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else NeonData.NEON_DATA
    override fun getPrimaryKey(): UniqueKey<DtPlayerProfileRecord> = PK_DT_PLAYER_PROFILE
    override fun getUniqueKeys(): List<UniqueKey<DtPlayerProfileRecord>> = listOf(UQ_DT_PLAYER_PROFILE_PLAYER_NAME)
    override fun getReferences(): List<ForeignKey<DtPlayerProfileRecord, *>> = listOf(FK_DT_PLAYER_PROFILE_DT_ROLE_ROLE_ID)

    private lateinit var _dtRole: DtRolePath

    /**
     * Get the implicit join path to the <code>NEON_DATA.DT_ROLE</code> table.
     */
    fun dtRole(): DtRolePath {
        if (!this::_dtRole.isInitialized)
            _dtRole = DtRolePath(this, FK_DT_PLAYER_PROFILE_DT_ROLE_ROLE_ID, null)

        return _dtRole;
    }

    val dtRole: DtRolePath
        get(): DtRolePath = dtRole()
    override fun `as`(alias: String): DtPlayerProfile = DtPlayerProfile(DSL.name(alias), this)
    override fun `as`(alias: Name): DtPlayerProfile = DtPlayerProfile(alias, this)
    override fun `as`(alias: Table<*>): DtPlayerProfile = DtPlayerProfile(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DtPlayerProfile = DtPlayerProfile(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DtPlayerProfile = DtPlayerProfile(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DtPlayerProfile = DtPlayerProfile(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): DtPlayerProfile = DtPlayerProfile(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DtPlayerProfile = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): DtPlayerProfile = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): DtPlayerProfile = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DtPlayerProfile = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DtPlayerProfile = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DtPlayerProfile = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DtPlayerProfile = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): DtPlayerProfile = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): DtPlayerProfile = where(DSL.notExists(select))
}
