package com.islandstudio.neon.api.dto.action

enum class ActionStatus {
    /* General action status */
    SUCCESS,
    FAILURE,

    RECORD_NOT_EXIST,
    DUPLICATE_RECORD,
    INVALID_REQUEST_FIELD,

    PLAYER_ROLE_ALREADY_ASSIGN,
    PLAYER_ROLE_NOT_ASSIGN,
    PLAYER_PROFILE_EXIST,
    PLAYER_PROFILE_NOT_EXIST,

    ROLE_EXIST,
    ROLE_NOT_EXIST,

    PERMISSION_EXIST,
    PERMISSION_NOT_EXIST,

    ROLE_PERMISSION_EXIST,
    ROLE_PERMISSION_NOT_EXIST,
    PARENT_PERMISSION_NOT_EXIST,
    PARENT_ROLE_PERMISSION_NOT_EXIST
}