/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables.records


import com.islandstudio.neon.apinew.schema.tables.PermissionTable
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PermissionRecord private constructor() : UpdatableRecordImpl<PermissionRecord>(PermissionTable.PERMISSION_TABLE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var parentid: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var name: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var code: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var description: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var createdby: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdat: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var modifiedby: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var modifiedat: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised PermissionRecord
     */
    constructor(id: Long?, parentid: Long?, name: String, code: String, description: String, createdby: String?, createdat: LocalDateTime?, modifiedby: String?, modifiedat: LocalDateTime?): this() {
        this.id = id
        this.parentid = parentid
        this.name = name
        this.code = code
        this.description = description
        this.createdby = createdby
        this.createdat = createdat
        this.modifiedby = modifiedby
        this.modifiedat = modifiedat
        resetChangedOnNotNull()
    }
}
