/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables.records


import com.islandstudio.neon.apinew.schema.tables.RolePermissionTable
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RolePermissionRecord private constructor() : UpdatableRecordImpl<RolePermissionRecord>(RolePermissionTable.ROLE_PERMISSION_TABLE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var parentid: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var roleid: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open var permissionid: Long
        set(value): Unit = set(3, value)
        get(): Long = get(3) as Long

    open var createdby: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var createdat: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var modifiedby: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var modifiedat: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised RolePermissionRecord
     */
    constructor(id: Long?, parentid: Long?, roleid: Long, permissionid: Long, createdby: String?, createdat: LocalDateTime?, modifiedby: String?, modifiedat: LocalDateTime?): this() {
        this.id = id
        this.parentid = parentid
        this.roleid = roleid
        this.permissionid = permissionid
        this.createdby = createdby
        this.createdat = createdat
        this.modifiedby = modifiedby
        this.modifiedat = modifiedat
        resetChangedOnNotNull()
    }
}
