/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables.references


import com.islandstudio.neon.apinew.schema.tables.PlayerProfileTable



/**
 * The table <code>PLAYER_PROFILE</code>.
 */
val PLAYER_PROFILE_TABLE: PlayerProfileTable = PlayerProfileTable.PLAYER_PROFILE_TABLE
