/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables.references


import com.islandstudio.neon.apinew.schema.tables.PlayerProfileTable
import com.islandstudio.neon.apinew.schema.tables.PlayerRoleTable



/**
 * The table <code>player_profile</code>.
 */
val PLAYER_PROFILE_TABLE: PlayerProfileTable = PlayerProfileTable.PLAYER_PROFILE_TABLE

/**
 * The table <code>player_role</code>.
 */
val PLAYER_ROLE_TABLE: PlayerRoleTable = PlayerRoleTable.PLAYER_ROLE_TABLE
