/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema


import com.islandstudio.neon.apinew.schema.tables.PlayerProfileTable
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA: DefaultSchema = DefaultSchema()
    }

    /**
     * The table <code>PLAYER_PROFILE</code>.
     */
    val PLAYER_PROFILE_TABLE: PlayerProfileTable get() = PlayerProfileTable.PLAYER_PROFILE_TABLE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        PlayerProfileTable.PLAYER_PROFILE_TABLE
    )
}
