/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.api.schema.neon_data.tables.references


import com.islandstudio.neon.api.schema.neon_data.tables.TPermission
import com.islandstudio.neon.api.schema.neon_data.tables.TPlayerProfile
import com.islandstudio.neon.api.schema.neon_data.tables.TRole
import com.islandstudio.neon.api.schema.neon_data.tables.TRolePermission



/**
 * The table <code>NEON_DATA.T_PERMISSION</code>.
 */
val T_PERMISSION: TPermission = TPermission.T_PERMISSION

/**
 * The table <code>NEON_DATA.T_PLAYER_PROFILE</code>.
 */
val T_PLAYER_PROFILE: TPlayerProfile = TPlayerProfile.T_PLAYER_PROFILE

/**
 * The table <code>NEON_DATA.T_ROLE</code>.
 */
val T_ROLE: TRole = TRole.T_ROLE

/**
 * The table <code>NEON_DATA.T_ROLE_PERMISSION</code>.
 */
val T_ROLE_PERMISSION: TRolePermission = TRolePermission.T_ROLE_PERMISSION
