/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.api.schema.neon_data.tables.records


import com.islandstudio.neon.api.schema.neon_data.tables.TRole
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TRoleRecord() : UpdatableRecordImpl<TRoleRecord>(TRole.T_ROLE) {

    open var roleId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var roleDisplayName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var roleCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var assignedPlayerCount: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var createdBy: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var modifiedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var modifiedBy: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised TRoleRecord
     */
    constructor(roleId: Long? = null, roleDisplayName: String? = null, roleCode: String? = null, assignedPlayerCount: Long? = null, createdAt: LocalDateTime? = null, createdBy: String? = null, modifiedAt: LocalDateTime? = null, modifiedBy: String? = null): this() {
        this.roleId = roleId
        this.roleDisplayName = roleDisplayName
        this.roleCode = roleCode
        this.assignedPlayerCount = assignedPlayerCount
        this.createdAt = createdAt
        this.createdBy = createdBy
        this.modifiedAt = modifiedAt
        this.modifiedBy = modifiedBy
        resetChangedOnNotNull()
    }
}
