/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.api.schema.neon_data.tables.records


import com.islandstudio.neon.api.schema.neon_data.tables.TRolePermission
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TRolePermissionRecord() : UpdatableRecordImpl<TRolePermissionRecord>(TRolePermission.T_ROLE_PERMISSION) {

    open var rolePermissionId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var roleId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var permissionId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var parentRolePermissionId: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var createdBy: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var modifiedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var modifiedBy: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised TRolePermissionRecord
     */
    constructor(rolePermissionId: Long? = null, roleId: Long? = null, permissionId: Long? = null, parentRolePermissionId: Long? = null, createdAt: LocalDateTime? = null, createdBy: String? = null, modifiedAt: LocalDateTime? = null, modifiedBy: String? = null): this() {
        this.rolePermissionId = rolePermissionId
        this.roleId = roleId
        this.permissionId = permissionId
        this.parentRolePermissionId = parentRolePermissionId
        this.createdAt = createdAt
        this.createdBy = createdBy
        this.modifiedAt = modifiedAt
        this.modifiedBy = modifiedBy
        resetChangedOnNotNull()
    }
}
