/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.stable.core.database.schema.neon_data.tables.records


import com.islandstudio.neon.stable.core.database.schema.neon_data.tables.DtAccessPermission
import com.islandstudio.neon.stable.core.database.schema.neon_data.tables.pojos.AccessPermission

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DtAccessPermissionRecord() : UpdatableRecordImpl<DtAccessPermissionRecord>(DtAccessPermission.DT_ACCESS_PERMISSION) {

    open var permissionId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var permissionName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var permissionCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var permissionDesc: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised DtAccessPermissionRecord
     */
    constructor(permissionId: Long? = null, permissionName: String? = null, permissionCode: String? = null, permissionDesc: String? = null): this() {
        this.permissionId = permissionId
        this.permissionName = permissionName
        this.permissionCode = permissionCode
        this.permissionDesc = permissionDesc
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised DtAccessPermissionRecord
     */
    constructor(value: AccessPermission?): this() {
        if (value != null) {
            this.permissionId = value.permissionId
            this.permissionName = value.permissionName
            this.permissionCode = value.permissionCode
            this.permissionDesc = value.permissionDesc
            resetChangedOnNotNull()
        }
    }
}
