/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.stable.core.database.schema.neon_data.tables.records


import com.islandstudio.neon.stable.core.database.schema.neon_data.tables.DtRole
import com.islandstudio.neon.stable.core.database.schema.neon_data.tables.pojos.Role

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DtRoleRecord() : UpdatableRecordImpl<DtRoleRecord>(DtRole.DT_ROLE) {

    open var roleId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var roleDisplayName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var roleCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var assignedPlayerCount: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var testcol: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised DtRoleRecord
     */
    constructor(roleId: Long? = null, roleDisplayName: String? = null, roleCode: String? = null, assignedPlayerCount: Long? = null, testcol: String? = null): this() {
        this.roleId = roleId
        this.roleDisplayName = roleDisplayName
        this.roleCode = roleCode
        this.assignedPlayerCount = assignedPlayerCount
        this.testcol = testcol
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised DtRoleRecord
     */
    constructor(value: Role?): this() {
        if (value != null) {
            this.roleId = value.roleId
            this.roleDisplayName = value.roleDisplayName
            this.roleCode = value.roleCode
            this.assignedPlayerCount = value.assignedPlayerCount
            this.testcol = value.testcol
            resetChangedOnNotNull()
        }
    }
}
