/* Table: player_profile */
CREATE TABLE IF NOT EXISTS player_profile(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    UUID VARCHAR(36) NOT NULL,
    Name VARCHAR(16) NOT NULL,
    JoinedAt DATETIME NOT NULL,
    RoleId BIGINT NULL DEFAULT NULL,
    CreatedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    ModifiedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    ModifiedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP()
);

/* Constraints [player_profile] */
ALTER TABLE IF EXISTS player_profile ADD CONSTRAINT FK_PLAYER_PROFILE_ROLE_ID FOREIGN KEY (RoleId)
    REFERENCES player_role(Id) ON DELETE CASCADE ON UPDATE CASCADE;

/* Table: player_role */
CREATE TABLE IF NOT EXISTS player_role(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DisplayName VARCHAR(64) NOT NULL,
    Code VARCHAR(64) NOT NULL,
    CreatedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    ModifiedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    ModifiedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP()
);

/* Constraints [player_role] */
ALTER TABLE player_role ADD CONSTRAINT UQ_PLAYER_ROLE_CODE UNIQUE (Code);

/* Table: permission */
CREATE TABLE IF NOT EXISTS permission(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ParentId BIGINT NULL DEFAULT NULL,
    Name VARCHAR(64) NOT NULL,
    Code VARCHAR(64) NOT NULL,
    Description TEXT NOT NULL,
    CreatedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    ModifiedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    ModifiedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP()
);

/* Constraints [permission] */
ALTER TABLE IF EXISTS permission ADD CONSTRAINT UQ_PERMISSION_NAME UNIQUE (Name);
ALTER TABLE IF EXISTS permission ADD CONSTRAINT UQ_PERMISSION_CODE UNIQUE (Code);

/* Table: role_permission */
CREATE TABLE IF NOT EXISTS role_permission(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    RoleId BIGINT NOT NULL,
    PermissionId BIGINT NOT NULL,
    CreatedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    ModifiedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    ModifiedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP()
);

/* Constraints [role_permission] */
ALTER TABLE IF EXISTS role_permission ADD CONSTRAINT FK_ROLE_PERMISSION_ROLE_ID FOREIGN KEY (RoleId)
REFERENCES player_role(Id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE IF EXISTS role_permission ADD CONSTRAINT FK_ROLE_PERMISSION_PERMISSION_ID FOREIGN KEY (PermissionId)
REFERENCES permission(Id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE IF EXISTS role_permission ADD CONSTRAINT UQ_ROLE_PERMISSION_ROLE_ID_PERMISSION_ID UNIQUE (RoleId, PermissionId);


