/* Table: player_profile */
CREATE TABLE IF NOT EXISTS player_profile(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    UUID VARCHAR(36) NOT NULL,
    Name VARCHAR(16) NOT NULL,
    JoinedAt DATETIME NOT NULL,
    RoleID BIGINT NULL DEFAULT NULL,
    CreatedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    ModifiedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    ModifiedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP()
    /*CONSTRAINT FK_PLAYER_PROFILE_ROLE_ID FOREIGN KEY (RoleID)
        REFERENCES player_role(ID) ON DELETE CASCADE ON UPDATE CASCADE*/
);

/* Table: player_role */
CREATE TABLE IF NOT EXISTS player_role(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DisplayName VARCHAR(64) NOT NULL,
    Code VARCHAR(64) NOT NULL,
    CreatedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    ModifiedBy VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    ModifiedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP()
);

ALTER TABLE player_profile ADD CONSTRAINT FK_PLAYER_PROFILE_ROLE_ID FOREIGN KEY (RoleID)
    REFERENCES player_role(ID) ON DELETE CASCADE ON UPDATE CASCADE;


