package com.islandstudio.neon.stable.core

import org.bukkit.Material

enum class NMaterial(val bukkitMaterial: Material?) {
    /* Wooden Planks */
    OAK_PLANKS(Material.getMaterial("OAK_PLANKS")),
    SPRUCE_PLANKS(Material.getMaterial("SPRUCE_PLANKS")),
    BIRCH_PLANKS(Material.getMaterial("BIRCH_PLANKS")),
    JUNGLE_PLANKS(Material.getMaterial("JUNGLE_PLANKS")),
    ACACIA_PLANKS(Material.getMaterial("ACACIA_PLANKS")),
    DARK_OAK_PLANKS(Material.getMaterial("DARK_OAK_PLANKS")),
    WARPED_PLANKS(Material.getMaterial("WARPED_PLANKS")),
    CRIMSON_PLANKS(Material.getMaterial("CRIMSON_PLANKS")),
    MANGROVE_PLANKS(Material.getMaterial("MANGROVE_PLANKS")),
    BAMBOO_PLANKS(Material.getMaterial("BAMBOO_PLANKS")),
    BAMBOO_MOSAIC(Material.getMaterial("BAMBOO_MOSAIC")),
    CHERRY_PLANKS(Material.getMaterial("CHERRY_PLANKS")),

    /* Wooden Stairs */
    OAK_STAIRS(Material.getMaterial("OAK_STAIRS")),
    SPRUCE_STAIRS(Material.getMaterial("SPRUCE_STAIRS")),
    BIRCH_STAIRS(Material.getMaterial("BIRCH_STAIRS")),
    JUNGLE_STAIRS(Material.getMaterial("JUNGLE_STAIRS")),
    ACACIA_STAIRS(Material.getMaterial("ACACIA_STAIRS")),
    DARK_OAK_STAIRS(Material.getMaterial("DARK_OAK_STAIRS")),
    WARPED_STAIRS(Material.getMaterial("WARPED_STAIRS")),
    CRIMSON_STAIRS(Material.getMaterial("CRIMSON_STAIRS")),
    MANGROVE_STAIRS(Material.getMaterial("MANGROVE_STAIRS")),
    BAMBOO_STAIRS(Material.getMaterial("BAMBOO_STAIRS")),
    BAMBOO_MOSAIC_STAIRS(Material.getMaterial("BAMBOO_MOSAIC_STAIRS")),
    CHERRY_STAIRS(Material.getMaterial("CHERRY_STAIRS")),

    /* Wooden Slab */
    OAK_SLAB(Material.getMaterial("OAK_SLAB")),
    SPRUCE_SLAB(Material.getMaterial("SPRUCE_SLAB")),
    BIRCH_SLAB(Material.getMaterial("BIRCH_SLAB")),
    JUNGLE_SLAB(Material.getMaterial("JUNGLE_SLAB")),
    ACACIA_SLAB(Material.getMaterial("ACACIA_SLAB")),
    DARK_OAK_SLAB(Material.getMaterial("DARK_OAK_SLAB")),
    WARPED_SLAB(Material.getMaterial("WARPED_SLAB")),
    CRIMSON_SLAB(Material.getMaterial("CRIMSON_SLAB")),
    MANGROVE_SLAB(Material.getMaterial("MANGROVE_SLAB")),
    BAMBOO_SLAB(Material.getMaterial("BAMBOO_SLAB")),
    BAMBOO_MOSAIC_SLAB(Material.getMaterial("BAMBOO_MOSAIC_SLAB")),
    CHERRY_SLAB(Material.getMaterial("CHERRY_SLAB")),

    /* Wooden Fence */
    OAK_FENCE(Material.getMaterial("OAK_FENCE")),
    SPRUCE_FENCE(Material.getMaterial("SPRUCE_FENCE")),
    BIRCH_FENCE(Material.getMaterial("BIRCH_FENCE")),
    JUNGLE_FENCE(Material.getMaterial("JUNGLE_FENCE")),
    ACACIA_FENCE(Material.getMaterial("ACACIA_FENCE")),
    DARK_OAK_FENCE(Material.getMaterial("DARK_OAK_FENCE")),
    WARPED_FENCE(Material.getMaterial("WARPED_FENCE")),
    CRIMSON_FENCE(Material.getMaterial("CRIMSON_FENCE")),
    MANGROVE_FENCE(Material.getMaterial("MANGROVE_FENCE")),
    BAMBOO_FENCE(Material.getMaterial("BAMBOO_FENCE")),
    CHERRY_FENCE(Material.getMaterial("CHERRY_FENCE")),

    /* Wooden Fence Gate */
    OAK_FENCE_GATE(Material.getMaterial("OAK_FENCE_GATE")),
    SPRUCE_FENCE_GATE(Material.getMaterial("SPRUCE_FENCE_GATE")),
    BIRCH_FENCE_GATE(Material.getMaterial("BIRCH_FENCE_GATE")),
    JUNGLE_FENCE_GATE(Material.getMaterial("JUNGLE_FENCE_GATE")),
    ACACIA_FENCE_GATE(Material.getMaterial("ACACIA_FENCE_GATE")),
    DARK_OAK_FENCE_GATE(Material.getMaterial("DARK_OAK_FENCE_GATE")),
    WARPED_FENCE_GATE(Material.getMaterial("WARPED_FENCE_GATE")),
    CRIMSON_FENCE_GATE(Material.getMaterial("CRIMSON_FENCE_GATE")),
    MANGROVE_FENCE_GATE(Material.getMaterial("MANGROVE_FENCE_GATE")),
    BAMBOO_FENCE_GATE(Material.getMaterial("BAMBOO_FENCE_GATE")),
    CHERRY_FENCE_GATE(Material.getMaterial("CHERRY_FENCE_GATE")),

    /* Wooden Door */
    OAK_DOOR(Material.getMaterial("OAK_DOOR")),
    SPRUCE_DOOR(Material.getMaterial("SPRUCE_DOOR")),
    BIRCH_DOOR(Material.getMaterial("BIRCH_DOOR")),
    JUNGLE_DOOR(Material.getMaterial("JUNGLE_DOOR")),
    ACACIA_DOOR(Material.getMaterial("ACACIA_DOOR")),
    DARK_OAK_DOOR(Material.getMaterial("DARK_OAK_DOOR")),
    WARPED_DOOR(Material.getMaterial("WARPED_DOOR")),
    CRIMSON_DOOR(Material.getMaterial("CRIMSON_DOOR")),
    MANGROVE_DOOR(Material.getMaterial("MANGROVE_DOOR")),
    BAMBOO_DOOR(Material.getMaterial("BAMBOO_DOOR")),
    CHERRY_DOOR(Material.getMaterial("CHERRY_DOOR")),

    /* Wooden Trap Door */
    OAK_TRAPDOOR(Material.getMaterial("OAK_TRAPDOOR")),
    SPRUCE_TRAPDOOR(Material.getMaterial("SPRUCE_TRAPDOOR")),
    BIRCH_TRAPDOOR(Material.getMaterial("BIRCH_TRAPDOOR")),
    JUNGLE_TRAPDOOR(Material.getMaterial("JUNGLE_TRAPDOOR")),
    ACACIA_TRAPDOOR(Material.getMaterial("ACACIA_TRAPDOOR")),
    DARK_OAK_TRAPDOOR(Material.getMaterial("DARK_OAK_TRAPDOOR")),
    WARPED_TRAPDOOR(Material.getMaterial("WARPED_TRAPDOOR")),
    CRIMSON_TRAPDOOR(Material.getMaterial("CRIMSON_TRAPDOOR")),
    MANGROVE_TRAPDOOR(Material.getMaterial("MANGROVE_TRAPDOOR")),
    BAMBOO_TRAPDOOR(Material.getMaterial("BAMBOO_TRAPDOOR")),
    CHERRY_TRAPDOOR(Material.getMaterial("CHERRY_TRAPDOOR")),

    /* Wooden Button */
    OAK_BUTTON(Material.getMaterial("OAK_BUTTON")),
    SPRUCE_BUTTON(Material.getMaterial("SPRUCE_BUTTON")),
    BIRCH_BUTTON(Material.getMaterial("BIRCH_BUTTON")),
    JUNGLE_BUTTON(Material.getMaterial("JUNGLE_BUTTON")),
    ACACIA_BUTTON(Material.getMaterial("ACACIA_BUTTON")),
    DARK_OAK_BUTTON(Material.getMaterial("DARK_OAK_BUTTON")),
    WARPED_BUTTON(Material.getMaterial("WARPED_BUTTON")),
    CRIMSON_BUTTON(Material.getMaterial("CRIMSON_BUTTON")),
    MANGROVE_BUTTON(Material.getMaterial("MANGROVE_BUTTON")),
    BAMBOO_BUTTON(Material.getMaterial("BAMBOO_BUTTON")),
    CHERRY_BUTTON(Material.getMaterial("CHERRY_BUTTON")),

    /* Wooden Pressure Plate */
    OAK_PRESSURE_PLATE(Material.getMaterial("OAK_PRESSURE_PLATE")),
    SPRUCE_PRESSURE_PLATE(Material.getMaterial("SPRUCE_PRESSURE_PLATE")),
    BIRCH_PRESSURE_PLATE(Material.getMaterial("BIRCH_PRESSURE_PLATE")),
    JUNGLE_PRESSURE_PLATE(Material.getMaterial("JUNGLE_PRESSURE_PLATE")),
    ACACIA_PRESSURE_PLATE(Material.getMaterial("ACACIA_PRESSURE_PLATE")),
    DARK_OAK_PRESSURE_PLATE(Material.getMaterial("DARK_OAK_PRESSURE_PLATE")),
    WARPED_PRESSURE_PLATE(Material.getMaterial("WARPED_PRESSURE_PLATE")),
    CRIMSON_PRESSURE_PLATE(Material.getMaterial("CRIMSON_PRESSURE_PLATE")),
    MANGROVE_PRESSURE_PLATE(Material.getMaterial("MANGROVE_PRESSURE_PLATE")),
    BAMBOO_PRESSURE_PLATE(Material.getMaterial("BAMBOO_PRESSURE_PLATE")),
    CHERRY_PRESSURE_PLATE(Material.getMaterial("CHERRY_PRESSURE_PLATE")),

    /* Wooden Sign */
    OAK_SIGN(Material.getMaterial("OAK_SIGN")),
    SPRUCE_SIGN(Material.getMaterial("SPRUCE_SIGN")),
    BIRCH_SIGN(Material.getMaterial("BIRCH_SIGN")),
    JUNGLE_SIGN(Material.getMaterial("JUNGLE_SIGN")),
    ACACIA_SIGN(Material.getMaterial("ACACIA_SIGN")),
    DARK_OAK_SIGN(Material.getMaterial("DARK_OAK_SIGN")),
    WARPED_SIGN(Material.getMaterial("WARPED_SIGN")),
    CRIMSON_SIGN(Material.getMaterial("CRIMSON_SIGN")),
    MANGROVE_SIGN(Material.getMaterial("MANGROVE_SIGN")),
    BAMBOO_SIGN(Material.getMaterial("BAMBOO_SIGN")),
    CHERRY_SIGN(Material.getMaterial("CHERRY_SIGN")),

    /* Wooden Boat */
    OAK_BOAT(Material.getMaterial("OAK_BOAT")),
    SPRUCE_BOAT(Material.getMaterial("SPRUCE_BOAT")),
    BIRCH_BOAT(Material.getMaterial("BIRCH_BOAT")),
    JUNGLE_BOAT(Material.getMaterial("JUNGLE_BOAT")),
    ACACIA_BOAT(Material.getMaterial("ACACIA_BOAT")),
    DARK_OAK_BOAT(Material.getMaterial("DARK_OAK_BOAT")),
    MANGROVE_BOAT(Material.getMaterial("MANGROVE_BOAT")),
    BAMBOO_RAFT(Material.getMaterial("BAMBOO_RAFT")),
    CHERRY_BOAT(Material.getMaterial("CHERRY_BOAT")),

    /* Wooden Items */
    STICK(Material.getMaterial("STICK")),
    LADDER(Material.getMaterial("LADDER")),
    BOWL(Material.getMaterial("BOWL")),

    /* Ingredient Items */
    CLAY_BALL(Material.getMaterial("CLAY_BALL")),
    NETHER_BRICK(Material.getMaterial("NETHER_BRICK")),
    CHARCOAL(Material.getMaterial("CHARCOAL")),

    /* Building Blocks */
    SAND(Material.getMaterial("SAND")),
    RED_SAND(Material.getMaterial("RED_SAND")),
    STONE(Material.getMaterial("STONE")),
    COBBLESTONE(Material.getMaterial("COBBLESTONE")),
    SANDSTONE(Material.getMaterial("SANDSTONE")),
    RED_SANDSTONE(Material.getMaterial("RED_SANDSTONE")),
    QUARTZ_BLOCK(Material.getMaterial("QUARTZ_BLOCK")),
    SMOOTH_SANDSTONE(Material.getMaterial("SMOOTH_SANDSTONE")),
    SMOOTH_RED_SANDSTONE(Material.getMaterial("SMOOTH_RED_SANDSTONE")),
    SMOOTH_STONE(Material.getMaterial("SMOOTH_STONE")),
    SMOOTH_QUARTZ(Material.getMaterial("SMOOTH_QUARTZ")),
    BRICK(Material.getMaterial("BRICK")),
    NETHER_BRICKS(Material.getMaterial("NETHER_BRICKS")),
    NETHERRACK(Material.getMaterial("NETHERRACK")),
    CRACKED_NETHER_BRICKS(Material.getMaterial("CRACKED_NETHER_BRICKS")),
    GLASS(Material.getMaterial("GLASS")),
    CLAY(Material.getMaterial("CLAY")),
    TERRACOTTA(Material.getMaterial("TERRACOTTA")),
    STONE_BRICKS(Material.getMaterial("STONE_BRICKS")),
    CRACKED_STONE_BRICKS(Material.getMaterial("CRACKED_STONE_BRICKS")),
    SPONGE(Material.getMaterial("SPONGE")),
    WET_SPONGE(Material.getMaterial("WET_SPONGE")),
    DEEPSLATE(Material.getMaterial("DEEPSLATE")),
    COBBLED_DEEPSLATE(Material.getMaterial("COBBLED_DEEPSLATE")),

    /* Ore Block */
    RAW_IRON_BLOCK(Material.getMaterial("RAW_IRON_BLOCK")),
    RAW_COPPER_BLOCK(Material.getMaterial("RAW_COPPER_BLOCK")),
    RAW_GOLD_BLOCK(Material.getMaterial("RAW_GOLD_BLOCK")),
    IRON_BLOCK(Material.getMaterial("IRON_BLOCK")),
    COPPER_BLOCK(Material.getMaterial("COPPER_BLOCK")),
    GOLD_BLOCK(Material.getMaterial("GOLD_BLOCK")),

    /* Colored Terracotta */
    WHITE_TERRACOTTA(Material.getMaterial("WHITE_TERRACOTTA")),
    ORANGE_TERRACOTTA(Material.getMaterial("ORANGE_TERRACOTTA")),
    MAGENTA_TERRACOTTA(Material.getMaterial("MAGENTA_TERRACOTTA")),
    LIGHT_BLUE_TERRACOTTA(Material.getMaterial("LIGHT_BLUE_TERRACOTTA")),
    YELLOW_TERRACOTTA(Material.getMaterial("YELLOW_TERRACOTTA")),
    LIME_TERRACOTTA(Material.getMaterial("LIME_TERRACOTTA")),
    PINK_TERRACOTTA(Material.getMaterial("PINK_TERRACOTTA")),
    GRAY_TERRACOTTA(Material.getMaterial("GRAY_TERRACOTTA")),
    LIGHT_GRAY_TERRACOTTA(Material.getMaterial("LIGHT_GRAY_TERRACOTTA")),
    CYAN_TERRACOTTA(Material.getMaterial("CYAN_TERRACOTTA")),
    PURPLE_TERRACOTTA(Material.getMaterial("PURPLE_TERRACOTTA")),
    BLUE_TERRACOTTA(Material.getMaterial("BLUE_TERRACOTTA")),
    BROWN_TERRACOTTA(Material.getMaterial("BROWN_TERRACOTTA")),
    GREEN_TERRACOTTA(Material.getMaterial("GREEN_TERRACOTTA")),
    RED_TERRACOTTA(Material.getMaterial("RED_TERRACOTTA")),
    BLACK_TERRACOTTA(Material.getMaterial("BLACK_TERRACOTTA")),

    /* Colored Glazed Terracotta */
    WHITE_GLAZED_TERRACOTTA(Material.getMaterial("WHITE_GLAZED_TERRACOTTA")),
    ORANGE_GLAZED_TERRACOTTA(Material.getMaterial("ORANGE_GLAZED_TERRACOTTA")),
    MAGENTA_GLAZED_TERRACOTTA(Material.getMaterial("MAGENTA_GLAZED_TERRACOTTA")),
    LIGHT_BLUE_GLAZED_TERRACOTTA(Material.getMaterial("LIGHT_BLUE_GLAZED_TERRACOTTA")),
    YELLOW_GLAZED_TERRACOTTA(Material.getMaterial("YELLOW_GLAZED_TERRACOTTA")),
    LIME_GLAZED_TERRACOTTA(Material.getMaterial("LIME_GLAZED_TERRACOTTA")),
    PINK_GLAZED_TERRACOTTA(Material.getMaterial("PINK_GLAZED_TERRACOTTA")),
    GRAY_GLAZED_TERRACOTTA(Material.getMaterial("GRAY_GLAZED_TERRACOTTA")),
    LIGHT_GRAY_GLAZED_TERRACOTTA(Material.getMaterial("LIGHT_GRAY_GLAZED_TERRACOTTA")),
    CYAN_GLAZED_TERRACOTTA(Material.getMaterial("CYAN_GLAZED_TERRACOTTA")),
    PURPLE_GLAZED_TERRACOTTA(Material.getMaterial("PURPLE_GLAZED_TERRACOTTA")),
    BLUE_GLAZED_TERRACOTTA(Material.getMaterial("BLUE_GLAZED_TERRACOTTA")),
    BROWN_GLAZED_TERRACOTTA(Material.getMaterial("BROWN_GLAZED_TERRACOTTA")),
    GREEN_GLAZED_TERRACOTTA(Material.getMaterial("GREEN_GLAZED_TERRACOTTA")),
    RED_GLAZED_TERRACOTTA(Material.getMaterial("RED_GLAZED_TERRACOTTA")),
    BLACK_GLAZED_TERRACOTTA(Material.getMaterial("BLACK_GLAZED_TERRACOTTA")),

    /* Dye */
    GREEN_DYE(Material.getMaterial("GREEN_DYE")),
    LIME_DYE(Material.getMaterial("LIME_DYE")),

    /* Plant */
    CACTUS(Material.getMaterial("CACTUS")),
    POPPED_CHORUS_FRUIT(Material.getMaterial("POPPED_CHORUS_FRUIT")),
    CHORUS_FRUIT(Material.getMaterial("CHORUS_FRUIT")),
    SEA_PICKLE(Material.getMaterial("SEA_PICKLE")),

    /* Wood */
    OAK_WOOD(Material.getMaterial("OAK_WOOD")),
    SPRUCE_WOOD(Material.getMaterial("SPRUCE_WOOD")),
    BIRCH_WOOD(Material.getMaterial("BIRCH_WOOD")),
    JUNGLE_WOOD(Material.getMaterial("JUNGLE_WOOD")),
    ACACIA_WOOD(Material.getMaterial("ACACIA_WOOD")),
    DARK_OAK_WOOD(Material.getMaterial("DARK_OAK_WOOD")),
    MANGROVE_WOOD(Material.getMaterial("MANGROVE_WOOD")),
    CHERRY_WOOD(Material.getMaterial("CHERRY_WOOD")),

    /* Wood Log */
    OAK_LOG(Material.getMaterial("OAK_LOG")),
    SPRUCE_LOG(Material.getMaterial("SPRUCE_LOG")),
    BIRCH_LOG(Material.getMaterial("BIRCH_LOG")),
    JUNGLE_LOG(Material.getMaterial("JUNGLE_LOG")),
    ACACIA_LOG(Material.getMaterial("ACACIA_LOG")),
    DARK_OAK_LOG(Material.getMaterial("DARK_OAK_LOG")),
    MANGROVE_LOG(Material.getMaterial("MANGROVE_LOG")),
    CHERRY_LOG(Material.getMaterial("CHERRY_LOG")),

    /* Stripped Wood */
    STRIPPED_OAK_WOOD(Material.getMaterial("STRIPPED_OAK_WOOD")),
    STRIPPED_SPRUCE_WOOD(Material.getMaterial("STRIPPED_SPRUCE_WOOD")),
    STRIPPED_BIRCH_WOOD(Material.getMaterial("STRIPPED_BIRCH_WOOD")),
    STRIPPED_JUNGLE_WOOD(Material.getMaterial("STRIPPED_JUNGLE_WOOD")),
    STRIPPED_ACACIA_WOOD(Material.getMaterial("STRIPPED_ACACIA_WOOD")),
    STRIPPED_DARK_OAK_WOOD(Material.getMaterial("STRIPPED_DARK_OAK_WOOD")),
    STRIPPED_MANGROVE_WOOD(Material.getMaterial("STRIPPED_MANGROVE_WOOD")),
    STRIPPED_CHERRY_WOOD(Material.getMaterial("STRIPPED_CHERRY_WOOD")),

    /* Stripped Log */
    STRIPPED_OAK_LOG(Material.getMaterial("STRIPPED_OAK_LOG")),
    STRIPPED_SPRUCE_LOG(Material.getMaterial("STRIPPED_SPRUCE_LOG")),
    STRIPPED_BIRCH_LOG(Material.getMaterial("STRIPPED_BIRCH_LOG")),
    STRIPPED_JUNGLE_LOG(Material.getMaterial("STRIPPED_JUNGLE_LOG")),
    STRIPPED_ACACIA_LOG(Material.getMaterial("STRIPPED_ACACIA_LOG")),
    STRIPPED_DARK_OAK_LOG(Material.getMaterial("STRIPPED_DARK_OAK_LOG")),
    STRIPPED_MANGROVE_LOG(Material.getMaterial("STRIPPED_MANGROVE_LOG")),
    STRIPPED_CHERRY_LOG(Material.getMaterial("STRIPPED_CHERRY_LOG")),

    DUMMY1(Material.getMaterial("DUMMY1")),
    DUMMY2(Material.getMaterial("DUMMY2")),
    DUMMY3(Material.getMaterial("DUMMY3"));
}