/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class AccessPermission(
    var permissionId: Long? = null,
    var permissionName: String? = null,
    var permissionCode: String? = null,
    var permissionDesc: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: AccessPermission = other as AccessPermission
        if (this.permissionId == null) {
            if (o.permissionId != null)
                return false
        }
        else if (this.permissionId != o.permissionId)
            return false
        if (this.permissionName == null) {
            if (o.permissionName != null)
                return false
        }
        else if (this.permissionName != o.permissionName)
            return false
        if (this.permissionCode == null) {
            if (o.permissionCode != null)
                return false
        }
        else if (this.permissionCode != o.permissionCode)
            return false
        if (this.permissionDesc == null) {
            if (o.permissionDesc != null)
                return false
        }
        else if (this.permissionDesc != o.permissionDesc)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.permissionId == null) 0 else this.permissionId.hashCode())
        result = prime * result + (if (this.permissionName == null) 0 else this.permissionName.hashCode())
        result = prime * result + (if (this.permissionCode == null) 0 else this.permissionCode.hashCode())
        result = prime * result + (if (this.permissionDesc == null) 0 else this.permissionDesc.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AccessPermission (")

        sb.append(permissionId)
        sb.append(", ").append(permissionName)
        sb.append(", ").append(permissionCode)
        sb.append(", ").append(permissionDesc)

        sb.append(")")
        return sb.toString()
    }
}
