/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class RoleAccess(
    var roleAccessId: Long? = null,
    var roleId: Long? = null,
    var permissionId: Long? = null,
    var accessType: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: RoleAccess = other as RoleAccess
        if (this.roleAccessId == null) {
            if (o.roleAccessId != null)
                return false
        }
        else if (this.roleAccessId != o.roleAccessId)
            return false
        if (this.roleId == null) {
            if (o.roleId != null)
                return false
        }
        else if (this.roleId != o.roleId)
            return false
        if (this.permissionId == null) {
            if (o.permissionId != null)
                return false
        }
        else if (this.permissionId != o.permissionId)
            return false
        if (this.accessType == null) {
            if (o.accessType != null)
                return false
        }
        else if (this.accessType != o.accessType)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.roleAccessId == null) 0 else this.roleAccessId.hashCode())
        result = prime * result + (if (this.roleId == null) 0 else this.roleId.hashCode())
        result = prime * result + (if (this.permissionId == null) 0 else this.permissionId.hashCode())
        result = prime * result + (if (this.accessType == null) 0 else this.accessType.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("RoleAccess (")

        sb.append(roleAccessId)
        sb.append(", ").append(roleId)
        sb.append(", ").append(permissionId)
        sb.append(", ").append(accessType)

        sb.append(")")
        return sb.toString()
    }
}
