name: Neon-Database-Server
author: ICities
version: '1.0'
api-version: '1.17'
depend: [Neon]
main: com.islandstudio.neondatabaseserver.NeonDatabaseServer
description: Database server for Neon plugin. [Require Neon plugin in order to work.]