/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.api.schema.neon_data.tables


import com.islandstudio.neon.api.schema.neon_data.NeonData
import com.islandstudio.neon.api.schema.neon_data.keys.FK_T_PLAYER_PROFILE_T_ROLE_ROLE_ID
import com.islandstudio.neon.api.schema.neon_data.keys.PK_T_PLAYER_PROFILE
import com.islandstudio.neon.api.schema.neon_data.keys.UQ_T_PLAYER_PROFILE_P_UUID_P_NAME
import com.islandstudio.neon.api.schema.neon_data.tables.TRole.TRolePath
import com.islandstudio.neon.api.schema.neon_data.tables.records.TPlayerProfileRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime
import java.util.*


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TPlayerProfile(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TPlayerProfileRecord>?,
    parentPath: InverseForeignKey<out Record, TPlayerProfileRecord>?,
    aliased: Table<TPlayerProfileRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TPlayerProfileRecord>(
    alias,
    NeonData.NEON_DATA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>NEON_DATA.T_PLAYER_PROFILE</code>
         */
        val T_PLAYER_PROFILE: TPlayerProfile = TPlayerProfile()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TPlayerProfileRecord> = TPlayerProfileRecord::class.java

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.ID</code>.
     */
    val ID: TableField<TPlayerProfileRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.PLAYER_UUID</code>.
     */
    val PLAYER_UUID: TableField<TPlayerProfileRecord, UUID?> = createField(DSL.name("PLAYER_UUID"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.PLAYER_NAME</code>.
     */
    val PLAYER_NAME: TableField<TPlayerProfileRecord, String?> = createField(DSL.name("PLAYER_NAME"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.JOIN_AT</code>.
     */
    val JOIN_AT: TableField<TPlayerProfileRecord, LocalDateTime?> = createField(DSL.name("JOIN_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.ROLE_ID</code>.
     */
    val ROLE_ID: TableField<TPlayerProfileRecord, Long?> = createField(DSL.name("ROLE_ID"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<TPlayerProfileRecord, LocalDateTime?> = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.CREATED_BY</code>.
     */
    val CREATED_BY: TableField<TPlayerProfileRecord, String?> = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.MODIFIED_AT</code>.
     */
    val MODIFIED_AT: TableField<TPlayerProfileRecord, LocalDateTime?> = createField(DSL.name("MODIFIED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>NEON_DATA.T_PLAYER_PROFILE.MODIFIED_BY</code>.
     */
    val MODIFIED_BY: TableField<TPlayerProfileRecord, String?> = createField(DSL.name("MODIFIED_BY"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<TPlayerProfileRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TPlayerProfileRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TPlayerProfileRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>NEON_DATA.T_PLAYER_PROFILE</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>NEON_DATA.T_PLAYER_PROFILE</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>NEON_DATA.T_PLAYER_PROFILE</code> table reference
     */
    constructor(): this(DSL.name("T_PLAYER_PROFILE"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TPlayerProfileRecord>?, parentPath: InverseForeignKey<out Record, TPlayerProfileRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, T_PLAYER_PROFILE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TPlayerProfilePath : TPlayerProfile, Path<TPlayerProfileRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TPlayerProfileRecord>?, parentPath: InverseForeignKey<out Record, TPlayerProfileRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TPlayerProfileRecord>): super(alias, aliased)
        override fun `as`(alias: String): TPlayerProfilePath = TPlayerProfilePath(DSL.name(alias), this)
        override fun `as`(alias: Name): TPlayerProfilePath = TPlayerProfilePath(alias, this)
        override fun `as`(alias: Table<*>): TPlayerProfilePath = TPlayerProfilePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else NeonData.NEON_DATA
    override fun getIdentity(): Identity<TPlayerProfileRecord, Long?> = super.getIdentity() as Identity<TPlayerProfileRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TPlayerProfileRecord> = PK_T_PLAYER_PROFILE
    override fun getUniqueKeys(): List<UniqueKey<TPlayerProfileRecord>> = listOf(UQ_T_PLAYER_PROFILE_P_UUID_P_NAME)
    override fun getReferences(): List<ForeignKey<TPlayerProfileRecord, *>> = listOf(FK_T_PLAYER_PROFILE_T_ROLE_ROLE_ID)

    private lateinit var _tRole: TRolePath

    /**
     * Get the implicit join path to the <code>NEON_DATA.T_ROLE</code> table.
     */
    fun tRole(): TRolePath {
        if (!this::_tRole.isInitialized)
            _tRole = TRolePath(this, FK_T_PLAYER_PROFILE_T_ROLE_ROLE_ID, null)

        return _tRole;
    }

    val tRole: TRolePath
        get(): TRolePath = tRole()
    override fun `as`(alias: String): TPlayerProfile = TPlayerProfile(DSL.name(alias), this)
    override fun `as`(alias: Name): TPlayerProfile = TPlayerProfile(alias, this)
    override fun `as`(alias: Table<*>): TPlayerProfile = TPlayerProfile(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TPlayerProfile = TPlayerProfile(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TPlayerProfile = TPlayerProfile(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TPlayerProfile = TPlayerProfile(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TPlayerProfile = TPlayerProfile(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TPlayerProfile = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TPlayerProfile = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TPlayerProfile = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TPlayerProfile = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TPlayerProfile = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TPlayerProfile = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TPlayerProfile = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TPlayerProfile = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TPlayerProfile = where(DSL.notExists(select))
}
