/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.api.schema


import com.islandstudio.neon.api.schema.neon_data.NeonData
import org.jooq.Constants
import org.jooq.Schema
import org.jooq.impl.CatalogImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class NeonDb : CatalogImpl("NEON_DB") {
    companion object {

        /**
         * The reference instance of <code>NEON_DB</code>
         */
        public val NEON_DB: NeonDb = NeonDb()
    }

    /**
     * The schema <code>NEON_DATA</code>.
     */
    val NEON_DATA: NeonData get(): NeonData = NeonData.NEON_DATA

    override fun getSchemas(): List<Schema> = listOf(
        NeonData.NEON_DATA
    )

    /**
     * A reference to the 3.19 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.19. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_19
}
