/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables


import com.islandstudio.neon.apinew.schema.DefaultSchema
import com.islandstudio.neon.apinew.schema.keys.*
import com.islandstudio.neon.apinew.schema.tables.PlayerRoleTable.PlayerRolePath
import com.islandstudio.neon.apinew.schema.tables.RolePermissionTable.RolePermissionPath
import com.islandstudio.neon.apinew.schema.tables.records.PermissionRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PermissionTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PermissionRecord>?,
    parentPath: InverseForeignKey<out Record, PermissionRecord>?,
    aliased: Table<PermissionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PermissionRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>permission</code>
         */
        val PERMISSION_TABLE: PermissionTable = PermissionTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PermissionRecord> = PermissionRecord::class.java

    /**
     * The column <code>permission.Id</code>.
     */
    val ID: TableField<PermissionRecord, Long?> = createField(DSL.name("Id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>permission.ParentId</code>.
     */
    val PARENTID: TableField<PermissionRecord, Long?> = createField(DSL.name("ParentId"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "")

    /**
     * The column <code>permission.Name</code>.
     */
    val NAME: TableField<PermissionRecord, String?> = createField(DSL.name("Name"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>permission.Code</code>.
     */
    val CODE: TableField<PermissionRecord, String?> = createField(DSL.name("Code"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>permission.Description</code>.
     */
    val DESCRIPTION: TableField<PermissionRecord, String?> = createField(DSL.name("Description"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>permission.CreatedBy</code>.
     */
    val CREATEDBY: TableField<PermissionRecord, String?> = createField(DSL.name("CreatedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>permission.CreatedAt</code>.
     */
    val CREATEDAT: TableField<PermissionRecord, LocalDateTime?> = createField(DSL.name("CreatedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>permission.ModifiedBy</code>.
     */
    val MODIFIEDBY: TableField<PermissionRecord, String?> = createField(DSL.name("ModifiedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>permission.ModifiedAt</code>.
     */
    val MODIFIEDAT: TableField<PermissionRecord, LocalDateTime?> = createField(DSL.name("ModifiedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<PermissionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PermissionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>permission</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>permission</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>permission</code> table reference
     */
    constructor(): this(DSL.name("permission"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PermissionRecord>?, parentPath: InverseForeignKey<out Record, PermissionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PERMISSION_TABLE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PermissionPath : PermissionTable, Path<PermissionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PermissionRecord>?, parentPath: InverseForeignKey<out Record, PermissionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PermissionRecord>): super(alias, aliased)
        override fun `as`(alias: String): PermissionPath = PermissionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PermissionPath = PermissionPath(alias, this)
        override fun `as`(alias: Table<*>): PermissionPath = PermissionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<PermissionRecord, Long?> = super.getIdentity() as Identity<PermissionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PermissionRecord> = KEY_PERMISSION_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<PermissionRecord>> = listOf(KEY_PERMISSION_UQ_PERMISSION_CODE, KEY_PERMISSION_UQ_PERMISSION_NAME)
    override fun getReferences(): List<ForeignKey<PermissionRecord, *>> = listOf(FK_PERMISSION_PARENT_ID)

    private lateinit var _permission: PermissionPath

    /**
     * Get the implicit join path to the <code>neon_dev.permission</code> table.
     */
    fun permission(): PermissionPath {
        if (!this::_permission.isInitialized)
            _permission = PermissionPath(this, FK_PERMISSION_PARENT_ID, null)

        return _permission;
    }

    val permission: PermissionPath
        get(): PermissionPath = permission()

    private lateinit var _rolePermission: RolePermissionPath

    /**
     * Get the implicit to-many join path to the
     * <code>neon_dev.role_permission</code> table
     */
    fun rolePermission(): RolePermissionPath {
        if (!this::_rolePermission.isInitialized)
            _rolePermission = RolePermissionPath(this, null, FK_ROLE_PERMISSION_PERMISSION_ID.inverseKey)

        return _rolePermission;
    }

    val rolePermission: RolePermissionPath
        get(): RolePermissionPath = rolePermission()

    /**
     * Get the implicit many-to-many join path to the
     * <code>neon_dev.player_role</code> table
     */
    val playerRole: PlayerRolePath
        get(): PlayerRolePath = rolePermission().playerRole()
    override fun `as`(alias: String): PermissionTable = PermissionTable(DSL.name(alias), this)
    override fun `as`(alias: Name): PermissionTable = PermissionTable(alias, this)
    override fun `as`(alias: Table<*>): PermissionTable = PermissionTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PermissionTable = PermissionTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PermissionTable = PermissionTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PermissionTable = PermissionTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PermissionTable = PermissionTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PermissionTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PermissionTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PermissionTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PermissionTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PermissionTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PermissionTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PermissionTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PermissionTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PermissionTable = where(DSL.notExists(select))
}
