/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables


import com.islandstudio.neon.apinew.schema.DefaultSchema
import com.islandstudio.neon.apinew.schema.keys.FK_PLAYER_PROFILE_ROLE_ID
import com.islandstudio.neon.apinew.schema.keys.FK_ROLE_PERMISSION_ROLE_ID
import com.islandstudio.neon.apinew.schema.keys.KEY_PLAYER_ROLE_PRIMARY
import com.islandstudio.neon.apinew.schema.keys.KEY_PLAYER_ROLE_UQ_PLAYER_ROLE_CODE
import com.islandstudio.neon.apinew.schema.tables.PermissionTable.PermissionPath
import com.islandstudio.neon.apinew.schema.tables.PlayerProfileTable.PlayerProfilePath
import com.islandstudio.neon.apinew.schema.tables.RolePermissionTable.RolePermissionPath
import com.islandstudio.neon.apinew.schema.tables.records.PlayerRoleRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerRoleTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerRoleRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerRoleRecord>?,
    aliased: Table<PlayerRoleRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerRoleRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>player_role</code>
         */
        val PLAYER_ROLE_TABLE: PlayerRoleTable = PlayerRoleTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerRoleRecord> = PlayerRoleRecord::class.java

    /**
     * The column <code>player_role.ID</code>.
     */
    val ID: TableField<PlayerRoleRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>player_role.DisplayName</code>.
     */
    val DISPLAYNAME: TableField<PlayerRoleRecord, String?> = createField(DSL.name("DisplayName"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>player_role.Code</code>.
     */
    val CODE: TableField<PlayerRoleRecord, String?> = createField(DSL.name("Code"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>player_role.CreatedBy</code>.
     */
    val CREATEDBY: TableField<PlayerRoleRecord, String?> = createField(DSL.name("CreatedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>player_role.CreatedAt</code>.
     */
    val CREATEDAT: TableField<PlayerRoleRecord, LocalDateTime?> = createField(DSL.name("CreatedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>player_role.ModifiedBy</code>.
     */
    val MODIFIEDBY: TableField<PlayerRoleRecord, String?> = createField(DSL.name("ModifiedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>player_role.ModifiedAt</code>.
     */
    val MODIFIEDAT: TableField<PlayerRoleRecord, LocalDateTime?> = createField(DSL.name("ModifiedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<PlayerRoleRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerRoleRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerRoleRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>player_role</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>player_role</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>player_role</code> table reference
     */
    constructor(): this(DSL.name("player_role"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerRoleRecord>?, parentPath: InverseForeignKey<out Record, PlayerRoleRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER_ROLE_TABLE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerRolePath : PlayerRoleTable, Path<PlayerRoleRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerRoleRecord>?, parentPath: InverseForeignKey<out Record, PlayerRoleRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerRoleRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerRolePath = PlayerRolePath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerRolePath = PlayerRolePath(alias, this)
        override fun `as`(alias: Table<*>): PlayerRolePath = PlayerRolePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<PlayerRoleRecord, Long?> = super.getIdentity() as Identity<PlayerRoleRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PlayerRoleRecord> = KEY_PLAYER_ROLE_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<PlayerRoleRecord>> = listOf(KEY_PLAYER_ROLE_UQ_PLAYER_ROLE_CODE)

    private lateinit var _playerProfile: PlayerProfilePath

    /**
     * Get the implicit to-many join path to the
     * <code>neon_dev.player_profile</code> table
     */
    fun playerProfile(): PlayerProfilePath {
        if (!this::_playerProfile.isInitialized)
            _playerProfile = PlayerProfilePath(this, null, FK_PLAYER_PROFILE_ROLE_ID.inverseKey)

        return _playerProfile;
    }

    val playerProfile: PlayerProfilePath
        get(): PlayerProfilePath = playerProfile()

    private lateinit var _rolePermission: RolePermissionPath

    /**
     * Get the implicit to-many join path to the
     * <code>neon_dev.role_permission</code> table
     */
    fun rolePermission(): RolePermissionPath {
        if (!this::_rolePermission.isInitialized)
            _rolePermission = RolePermissionPath(this, null, FK_ROLE_PERMISSION_ROLE_ID.inverseKey)

        return _rolePermission;
    }

    val rolePermission: RolePermissionPath
        get(): RolePermissionPath = rolePermission()

    /**
     * Get the implicit many-to-many join path to the
     * <code>neon_dev.permission</code> table
     */
    val permission: PermissionPath
        get(): PermissionPath = rolePermission().permission()
    override fun `as`(alias: String): PlayerRoleTable = PlayerRoleTable(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerRoleTable = PlayerRoleTable(alias, this)
    override fun `as`(alias: Table<*>): PlayerRoleTable = PlayerRoleTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerRoleTable = PlayerRoleTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerRoleTable = PlayerRoleTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerRoleTable = PlayerRoleTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerRoleTable = PlayerRoleTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerRoleTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerRoleTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerRoleTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerRoleTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerRoleTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerRoleTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerRoleTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerRoleTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerRoleTable = where(DSL.notExists(select))
}
