/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables


import com.islandstudio.neon.apinew.schema.DefaultSchema
import com.islandstudio.neon.apinew.schema.keys.FK_PLAYER_PROFILE_ROLE_ID
import com.islandstudio.neon.apinew.schema.keys.KEY_PLAYER_PROFILE_PRIMARY
import com.islandstudio.neon.apinew.schema.tables.PlayerRoleTable.PlayerRolePath
import com.islandstudio.neon.apinew.schema.tables.records.PlayerProfileRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerProfileTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerProfileRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerProfileRecord>?,
    aliased: Table<PlayerProfileRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerProfileRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>player_profile</code>
         */
        val PLAYER_PROFILE_TABLE: PlayerProfileTable = PlayerProfileTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerProfileRecord> = PlayerProfileRecord::class.java

    /**
     * The column <code>player_profile.ID</code>.
     */
    val ID: TableField<PlayerProfileRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>player_profile.UUID</code>.
     */
    val UUID: TableField<PlayerProfileRecord, String?> = createField(DSL.name("UUID"), SQLDataType.VARCHAR(36).nullable(false), this, "")

    /**
     * The column <code>player_profile.Name</code>.
     */
    val NAME: TableField<PlayerProfileRecord, String?> = createField(DSL.name("Name"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>player_profile.JoinedAt</code>.
     */
    val JOINEDAT: TableField<PlayerProfileRecord, LocalDateTime?> = createField(DSL.name("JoinedAt"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "")

    /**
     * The column <code>player_profile.RoleID</code>.
     */
    val ROLEID: TableField<PlayerProfileRecord, Long?> = createField(DSL.name("RoleID"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "")

    /**
     * The column <code>player_profile.CreatedBy</code>.
     */
    val CREATEDBY: TableField<PlayerProfileRecord, String?> = createField(DSL.name("CreatedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>player_profile.CreatedAt</code>.
     */
    val CREATEDAT: TableField<PlayerProfileRecord, LocalDateTime?> = createField(DSL.name("CreatedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>player_profile.ModifiedBy</code>.
     */
    val MODIFIEDBY: TableField<PlayerProfileRecord, String?> = createField(DSL.name("ModifiedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>player_profile.ModifiedAt</code>.
     */
    val MODIFIEDAT: TableField<PlayerProfileRecord, LocalDateTime?> = createField(DSL.name("ModifiedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<PlayerProfileRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerProfileRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerProfileRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>player_profile</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>player_profile</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>player_profile</code> table reference
     */
    constructor(): this(DSL.name("player_profile"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerProfileRecord>?, parentPath: InverseForeignKey<out Record, PlayerProfileRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER_PROFILE_TABLE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerProfilePath : PlayerProfileTable, Path<PlayerProfileRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerProfileRecord>?, parentPath: InverseForeignKey<out Record, PlayerProfileRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerProfileRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerProfilePath = PlayerProfilePath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerProfilePath = PlayerProfilePath(alias, this)
        override fun `as`(alias: Table<*>): PlayerProfilePath = PlayerProfilePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<PlayerProfileRecord, Long?> = super.getIdentity() as Identity<PlayerProfileRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PlayerProfileRecord> = KEY_PLAYER_PROFILE_PRIMARY
    override fun getReferences(): List<ForeignKey<PlayerProfileRecord, *>> = listOf(FK_PLAYER_PROFILE_ROLE_ID)

    private lateinit var _playerRole: PlayerRolePath

    /**
     * Get the implicit join path to the <code>neon_dev.player_role</code>
     * table.
     */
    fun playerRole(): PlayerRolePath {
        if (!this::_playerRole.isInitialized)
            _playerRole = PlayerRolePath(this, FK_PLAYER_PROFILE_ROLE_ID, null)

        return _playerRole;
    }

    val playerRole: PlayerRolePath
        get(): PlayerRolePath = playerRole()
    override fun `as`(alias: String): PlayerProfileTable = PlayerProfileTable(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerProfileTable = PlayerProfileTable(alias, this)
    override fun `as`(alias: Table<*>): PlayerProfileTable = PlayerProfileTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerProfileTable = PlayerProfileTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerProfileTable = PlayerProfileTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerProfileTable = PlayerProfileTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerProfileTable = PlayerProfileTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerProfileTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerProfileTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerProfileTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerProfileTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerProfileTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerProfileTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerProfileTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerProfileTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerProfileTable = where(DSL.notExists(select))
}
