/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables


import com.islandstudio.neon.apinew.schema.DefaultSchema
import com.islandstudio.neon.apinew.schema.keys.CONSTRAINT_1
import com.islandstudio.neon.apinew.schema.tables.records.PlayerProfileRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerProfileTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerProfileRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerProfileRecord>?,
    aliased: Table<PlayerProfileRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerProfileRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PLAYER_PROFILE</code>
         */
        val PLAYER_PROFILE_TABLE: PlayerProfileTable = PlayerProfileTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerProfileRecord> = PlayerProfileRecord::class.java

    /**
     * The column <code>PLAYER_PROFILE.ID</code>.
     */
    val ID: TableField<PlayerProfileRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>PLAYER_PROFILE.UUID</code>.
     */
    val UUID: TableField<PlayerProfileRecord, String?> = createField(DSL.name("UUID"), SQLDataType.VARCHAR(36).nullable(false), this, "")

    /**
     * The column <code>PLAYER_PROFILE.NAME</code>.
     */
    val NAME: TableField<PlayerProfileRecord, String?> = createField(DSL.name("NAME"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>PLAYER_PROFILE.JOINED_AT</code>.
     */
    val JOINED_AT: TableField<PlayerProfileRecord, LocalDateTime?> = createField(DSL.name("JOINED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>PLAYER_PROFILE.ROLE_ID</code>.
     */
    val ROLE_ID: TableField<PlayerProfileRecord, Long?> = createField(DSL.name("ROLE_ID"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "")

    /**
     * The column <code>PLAYER_PROFILE.CREATED_BY</code>.
     */
    val CREATED_BY: TableField<PlayerProfileRecord, String?> = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>PLAYER_PROFILE.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<PlayerProfileRecord, LocalDateTime?> = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>PLAYER_PROFILE.MODIFIED_BY</code>.
     */
    val MODIFIED_BY: TableField<PlayerProfileRecord, String?> = createField(DSL.name("MODIFIED_BY"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>PLAYER_PROFILE.MODIFIED_AT</code>.
     */
    val MODIFIED_AT: TableField<PlayerProfileRecord, LocalDateTime?> = createField(DSL.name("MODIFIED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerProfileRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerProfileRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerProfileRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PLAYER_PROFILE</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PLAYER_PROFILE</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PLAYER_PROFILE</code> table reference
     */
    constructor(): this(DSL.name("PLAYER_PROFILE"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<PlayerProfileRecord, Long?> = super.getIdentity() as Identity<PlayerProfileRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PlayerProfileRecord> = CONSTRAINT_1
    override fun `as`(alias: String): PlayerProfileTable = PlayerProfileTable(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerProfileTable = PlayerProfileTable(alias, this)
    override fun `as`(alias: Table<*>): PlayerProfileTable = PlayerProfileTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerProfileTable = PlayerProfileTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerProfileTable = PlayerProfileTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerProfileTable = PlayerProfileTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerProfileTable = PlayerProfileTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerProfileTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerProfileTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerProfileTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerProfileTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerProfileTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerProfileTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerProfileTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerProfileTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerProfileTable = where(DSL.notExists(select))
}
