/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.tables


import com.islandstudio.neon.apinew.schema.DefaultSchema
import com.islandstudio.neon.apinew.schema.keys.FK_ROLE_PERMISSION_PERMISSION_ID
import com.islandstudio.neon.apinew.schema.keys.FK_ROLE_PERMISSION_ROLE_ID
import com.islandstudio.neon.apinew.schema.keys.KEY_ROLE_PERMISSION_PRIMARY
import com.islandstudio.neon.apinew.schema.keys.KEY_ROLE_PERMISSION_UQ_ROLE_PERMISSION_ROLE_ID_PERMISSION_ID
import com.islandstudio.neon.apinew.schema.tables.PermissionTable.PermissionPath
import com.islandstudio.neon.apinew.schema.tables.PlayerRoleTable.PlayerRolePath
import com.islandstudio.neon.apinew.schema.tables.records.RolePermissionRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RolePermissionTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RolePermissionRecord>?,
    parentPath: InverseForeignKey<out Record, RolePermissionRecord>?,
    aliased: Table<RolePermissionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RolePermissionRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>role_permission</code>
         */
        val ROLE_PERMISSION_TABLE: RolePermissionTable = RolePermissionTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RolePermissionRecord> = RolePermissionRecord::class.java

    /**
     * The column <code>role_permission.Id</code>.
     */
    val ID: TableField<RolePermissionRecord, Long?> = createField(DSL.name("Id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>role_permission.RoleId</code>.
     */
    val ROLEID: TableField<RolePermissionRecord, Long?> = createField(DSL.name("RoleId"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>role_permission.PermissionId</code>.
     */
    val PERMISSIONID: TableField<RolePermissionRecord, Long?> = createField(DSL.name("PermissionId"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>role_permission.CreatedBy</code>.
     */
    val CREATEDBY: TableField<RolePermissionRecord, String?> = createField(DSL.name("CreatedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>role_permission.CreatedAt</code>.
     */
    val CREATEDAT: TableField<RolePermissionRecord, LocalDateTime?> = createField(DSL.name("CreatedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>role_permission.ModifiedBy</code>.
     */
    val MODIFIEDBY: TableField<RolePermissionRecord, String?> = createField(DSL.name("ModifiedBy"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>role_permission.ModifiedAt</code>.
     */
    val MODIFIEDAT: TableField<RolePermissionRecord, LocalDateTime?> = createField(DSL.name("ModifiedAt"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("utc_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<RolePermissionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RolePermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RolePermissionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>role_permission</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>role_permission</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>role_permission</code> table reference
     */
    constructor(): this(DSL.name("role_permission"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RolePermissionRecord>?, parentPath: InverseForeignKey<out Record, RolePermissionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ROLE_PERMISSION_TABLE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RolePermissionPath : RolePermissionTable, Path<RolePermissionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RolePermissionRecord>?, parentPath: InverseForeignKey<out Record, RolePermissionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RolePermissionRecord>): super(alias, aliased)
        override fun `as`(alias: String): RolePermissionPath = RolePermissionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RolePermissionPath = RolePermissionPath(alias, this)
        override fun `as`(alias: Table<*>): RolePermissionPath = RolePermissionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<RolePermissionRecord, Long?> = super.getIdentity() as Identity<RolePermissionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<RolePermissionRecord> = KEY_ROLE_PERMISSION_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<RolePermissionRecord>> = listOf(KEY_ROLE_PERMISSION_UQ_ROLE_PERMISSION_ROLE_ID_PERMISSION_ID)
    override fun getReferences(): List<ForeignKey<RolePermissionRecord, *>> = listOf(FK_ROLE_PERMISSION_PERMISSION_ID, FK_ROLE_PERMISSION_ROLE_ID)

    private lateinit var _permission: PermissionPath

    /**
     * Get the implicit join path to the <code>neon_dev.permission</code> table.
     */
    fun permission(): PermissionPath {
        if (!this::_permission.isInitialized)
            _permission = PermissionPath(this, FK_ROLE_PERMISSION_PERMISSION_ID, null)

        return _permission;
    }

    val permission: PermissionPath
        get(): PermissionPath = permission()

    private lateinit var _playerRole: PlayerRolePath

    /**
     * Get the implicit join path to the <code>neon_dev.player_role</code>
     * table.
     */
    fun playerRole(): PlayerRolePath {
        if (!this::_playerRole.isInitialized)
            _playerRole = PlayerRolePath(this, FK_ROLE_PERMISSION_ROLE_ID, null)

        return _playerRole;
    }

    val playerRole: PlayerRolePath
        get(): PlayerRolePath = playerRole()
    override fun `as`(alias: String): RolePermissionTable = RolePermissionTable(DSL.name(alias), this)
    override fun `as`(alias: Name): RolePermissionTable = RolePermissionTable(alias, this)
    override fun `as`(alias: Table<*>): RolePermissionTable = RolePermissionTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RolePermissionTable = RolePermissionTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RolePermissionTable = RolePermissionTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RolePermissionTable = RolePermissionTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): RolePermissionTable = RolePermissionTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): RolePermissionTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): RolePermissionTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): RolePermissionTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): RolePermissionTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): RolePermissionTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): RolePermissionTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): RolePermissionTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): RolePermissionTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): RolePermissionTable = where(DSL.notExists(select))
}
