/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.keys


import com.islandstudio.neon.apinew.schema.tables.PlayerProfileTable
import com.islandstudio.neon.apinew.schema.tables.records.PlayerProfileRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val CONSTRAINT_1: UniqueKey<PlayerProfileRecord> = Internal.createUniqueKey(PlayerProfileTable.PLAYER_PROFILE_TABLE, DSL.name("CONSTRAINT_1"), arrayOf(PlayerProfileTable.PLAYER_PROFILE_TABLE.ID), true)
