/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.keys


import com.islandstudio.neon.apinew.schema.tables.PlayerProfileTable
import com.islandstudio.neon.apinew.schema.tables.PlayerRoleTable
import com.islandstudio.neon.apinew.schema.tables.records.PlayerProfileRecord
import com.islandstudio.neon.apinew.schema.tables.records.PlayerRoleRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val KEY_PLAYER_PROFILE_PRIMARY: UniqueKey<PlayerProfileRecord> = Internal.createUniqueKey(PlayerProfileTable.PLAYER_PROFILE_TABLE, DSL.name("KEY_player_profile_PRIMARY"), arrayOf(PlayerProfileTable.PLAYER_PROFILE_TABLE.ID), true)
val KEY_PLAYER_ROLE_PRIMARY: UniqueKey<PlayerRoleRecord> = Internal.createUniqueKey(PlayerRoleTable.PLAYER_ROLE_TABLE, DSL.name("KEY_player_role_PRIMARY"), arrayOf(PlayerRoleTable.PLAYER_ROLE_TABLE.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val FK_PLAYER_PROFILE_ROLE_ID: ForeignKey<PlayerProfileRecord, PlayerRoleRecord> = Internal.createForeignKey(PlayerProfileTable.PLAYER_PROFILE_TABLE, DSL.name("FK_PLAYER_PROFILE_ROLE_ID"), arrayOf(PlayerProfileTable.PLAYER_PROFILE_TABLE.ROLEID), com.islandstudio.neon.apinew.schema.keys.KEY_PLAYER_ROLE_PRIMARY, arrayOf(PlayerRoleTable.PLAYER_ROLE_TABLE.ID), true)
