/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.apinew.schema.keys


import com.islandstudio.neon.apinew.schema.tables.PermissionTable
import com.islandstudio.neon.apinew.schema.tables.PlayerProfileTable
import com.islandstudio.neon.apinew.schema.tables.PlayerRoleTable
import com.islandstudio.neon.apinew.schema.tables.RolePermissionTable
import com.islandstudio.neon.apinew.schema.tables.records.PermissionRecord
import com.islandstudio.neon.apinew.schema.tables.records.PlayerProfileRecord
import com.islandstudio.neon.apinew.schema.tables.records.PlayerRoleRecord
import com.islandstudio.neon.apinew.schema.tables.records.RolePermissionRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val KEY_PERMISSION_PRIMARY: UniqueKey<PermissionRecord> = Internal.createUniqueKey(PermissionTable.PERMISSION_TABLE, DSL.name("KEY_permission_PRIMARY"), arrayOf(PermissionTable.PERMISSION_TABLE.ID), true)
val KEY_PERMISSION_UQ_PERMISSION_CODE: UniqueKey<PermissionRecord> = Internal.createUniqueKey(PermissionTable.PERMISSION_TABLE, DSL.name("KEY_permission_UQ_PERMISSION_CODE"), arrayOf(PermissionTable.PERMISSION_TABLE.CODE), true)
val KEY_PERMISSION_UQ_PERMISSION_NAME: UniqueKey<PermissionRecord> = Internal.createUniqueKey(PermissionTable.PERMISSION_TABLE, DSL.name("KEY_permission_UQ_PERMISSION_NAME"), arrayOf(PermissionTable.PERMISSION_TABLE.NAME), true)
val KEY_PLAYER_PROFILE_PRIMARY: UniqueKey<PlayerProfileRecord> = Internal.createUniqueKey(PlayerProfileTable.PLAYER_PROFILE_TABLE, DSL.name("KEY_player_profile_PRIMARY"), arrayOf(PlayerProfileTable.PLAYER_PROFILE_TABLE.ID), true)
val KEY_PLAYER_ROLE_PRIMARY: UniqueKey<PlayerRoleRecord> = Internal.createUniqueKey(PlayerRoleTable.PLAYER_ROLE_TABLE, DSL.name("KEY_player_role_PRIMARY"), arrayOf(PlayerRoleTable.PLAYER_ROLE_TABLE.ID), true)
val KEY_PLAYER_ROLE_UQ_PLAYER_ROLE_CODE: UniqueKey<PlayerRoleRecord> = Internal.createUniqueKey(PlayerRoleTable.PLAYER_ROLE_TABLE, DSL.name("KEY_player_role_UQ_PLAYER_ROLE_CODE"), arrayOf(PlayerRoleTable.PLAYER_ROLE_TABLE.CODE), true)
val KEY_ROLE_PERMISSION_PRIMARY: UniqueKey<RolePermissionRecord> = Internal.createUniqueKey(RolePermissionTable.ROLE_PERMISSION_TABLE, DSL.name("KEY_role_permission_PRIMARY"), arrayOf(RolePermissionTable.ROLE_PERMISSION_TABLE.ID), true)
val KEY_ROLE_PERMISSION_UQ_ROLE_PERMISSION_ROLE_ID_PERMISSION_ID: UniqueKey<RolePermissionRecord> = Internal.createUniqueKey(RolePermissionTable.ROLE_PERMISSION_TABLE, DSL.name("KEY_role_permission_UQ_ROLE_PERMISSION_ROLE_ID_PERMISSION_ID"), arrayOf(RolePermissionTable.ROLE_PERMISSION_TABLE.ROLEID, RolePermissionTable.ROLE_PERMISSION_TABLE.PERMISSIONID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val FK_PLAYER_PROFILE_ROLE_ID: ForeignKey<PlayerProfileRecord, PlayerRoleRecord> = Internal.createForeignKey(PlayerProfileTable.PLAYER_PROFILE_TABLE, DSL.name("FK_PLAYER_PROFILE_ROLE_ID"), arrayOf(PlayerProfileTable.PLAYER_PROFILE_TABLE.ROLEID), com.islandstudio.neon.apinew.schema.keys.KEY_PLAYER_ROLE_PRIMARY, arrayOf(PlayerRoleTable.PLAYER_ROLE_TABLE.ID), true)
val FK_ROLE_PERMISSION_PERMISSION_ID: ForeignKey<RolePermissionRecord, PermissionRecord> = Internal.createForeignKey(RolePermissionTable.ROLE_PERMISSION_TABLE, DSL.name("FK_ROLE_PERMISSION_PERMISSION_ID"), arrayOf(RolePermissionTable.ROLE_PERMISSION_TABLE.PERMISSIONID), com.islandstudio.neon.apinew.schema.keys.KEY_PERMISSION_PRIMARY, arrayOf(PermissionTable.PERMISSION_TABLE.ID), true)
val FK_ROLE_PERMISSION_ROLE_ID: ForeignKey<RolePermissionRecord, PlayerRoleRecord> = Internal.createForeignKey(RolePermissionTable.ROLE_PERMISSION_TABLE, DSL.name("FK_ROLE_PERMISSION_ROLE_ID"), arrayOf(RolePermissionTable.ROLE_PERMISSION_TABLE.ROLEID), com.islandstudio.neon.apinew.schema.keys.KEY_PLAYER_ROLE_PRIMARY, arrayOf(PlayerRoleTable.PLAYER_ROLE_TABLE.ID), true)
