/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables


import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.NeonData
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.keys.FK_DT_ROLE_ACCESS_PERMISSION__DT_ACCESS_PERMISSION_PERMISSION_ID
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.keys.PK_DT_ACCESS_PERMISSION
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.keys.UQ_DT_ACCESS_PERMISSION_PERMISSION_CODE
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.keys.UQ_DT_ACCESS_PERMISSION_PERMISSION_NAME
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.DtRole.DtRolePath
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.DtRoleAccess.DtRoleAccessPath
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.records.DtAccessPermissionRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DtAccessPermission(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DtAccessPermissionRecord>?,
    parentPath: InverseForeignKey<out Record, DtAccessPermissionRecord>?,
    aliased: Table<DtAccessPermissionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DtAccessPermissionRecord>(
    alias,
    NeonData.NEON_DATA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>NEON_DATA.DT_ACCESS_PERMISSION</code>
         */
        val DT_ACCESS_PERMISSION: DtAccessPermission = DtAccessPermission()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DtAccessPermissionRecord> = DtAccessPermissionRecord::class.java

    /**
     * The column <code>NEON_DATA.DT_ACCESS_PERMISSION.PERMISSION_ID</code>.
     */
    val PERMISSION_ID: TableField<DtAccessPermissionRecord, Long?> = createField(DSL.name("PERMISSION_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>NEON_DATA.DT_ACCESS_PERMISSION.PERMISSION_NAME</code>.
     */
    val PERMISSION_NAME: TableField<DtAccessPermissionRecord, String?> = createField(DSL.name("PERMISSION_NAME"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>NEON_DATA.DT_ACCESS_PERMISSION.PERMISSION_CODE</code>.
     */
    val PERMISSION_CODE: TableField<DtAccessPermissionRecord, String?> = createField(DSL.name("PERMISSION_CODE"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>NEON_DATA.DT_ACCESS_PERMISSION.PERMISSION_DESC</code>.
     */
    val PERMISSION_DESC: TableField<DtAccessPermissionRecord, String?> = createField(DSL.name("PERMISSION_DESC"), SQLDataType.VARCHAR(1000000000), this, "")

    private constructor(alias: Name, aliased: Table<DtAccessPermissionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DtAccessPermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DtAccessPermissionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>NEON_DATA.DT_ACCESS_PERMISSION</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>NEON_DATA.DT_ACCESS_PERMISSION</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>NEON_DATA.DT_ACCESS_PERMISSION</code> table reference
     */
    constructor(): this(DSL.name("DT_ACCESS_PERMISSION"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DtAccessPermissionRecord>?, parentPath: InverseForeignKey<out Record, DtAccessPermissionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, DT_ACCESS_PERMISSION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class DtAccessPermissionPath : DtAccessPermission, Path<DtAccessPermissionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DtAccessPermissionRecord>?, parentPath: InverseForeignKey<out Record, DtAccessPermissionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<DtAccessPermissionRecord>): super(alias, aliased)
        override fun `as`(alias: String): DtAccessPermissionPath = DtAccessPermissionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): DtAccessPermissionPath = DtAccessPermissionPath(alias, this)
        override fun `as`(alias: Table<*>): DtAccessPermissionPath = DtAccessPermissionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else NeonData.NEON_DATA
    override fun getIdentity(): Identity<DtAccessPermissionRecord, Long?> = super.getIdentity() as Identity<DtAccessPermissionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<DtAccessPermissionRecord> = PK_DT_ACCESS_PERMISSION
    override fun getUniqueKeys(): List<UniqueKey<DtAccessPermissionRecord>> = listOf(UQ_DT_ACCESS_PERMISSION_PERMISSION_CODE, UQ_DT_ACCESS_PERMISSION_PERMISSION_NAME)

    private lateinit var _dtRoleAccess: DtRoleAccessPath

    /**
     * Get the implicit to-many join path to the
     * <code>NEON_DATA.DT_ROLE_ACCESS</code> table
     */
    fun dtRoleAccess(): DtRoleAccessPath {
        if (!this::_dtRoleAccess.isInitialized)
            _dtRoleAccess = DtRoleAccessPath(this, null, FK_DT_ROLE_ACCESS_PERMISSION__DT_ACCESS_PERMISSION_PERMISSION_ID.inverseKey)

        return _dtRoleAccess;
    }

    val dtRoleAccess: DtRoleAccessPath
        get(): DtRoleAccessPath = dtRoleAccess()

    /**
     * Get the implicit many-to-many join path to the
     * <code>NEON_DATA.DT_ROLE</code> table
     */
    val dtRole: DtRolePath
        get(): DtRolePath = dtRoleAccess().dtRole()
    override fun getChecks(): List<Check<DtAccessPermissionRecord>> = listOf(
        Internal.createCheck(this, DSL.name("DT_ACCESS_PERMISSION_ENSURE_LOWERCASE"), "\"PERMISSION_CODE\" = UPPER(\"PERMISSION_CODE\")", true)
    )
    override fun `as`(alias: String): DtAccessPermission = DtAccessPermission(DSL.name(alias), this)
    override fun `as`(alias: Name): DtAccessPermission = DtAccessPermission(alias, this)
    override fun `as`(alias: Table<*>): DtAccessPermission = DtAccessPermission(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DtAccessPermission = DtAccessPermission(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DtAccessPermission = DtAccessPermission(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DtAccessPermission = DtAccessPermission(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): DtAccessPermission = DtAccessPermission(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DtAccessPermission = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): DtAccessPermission = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): DtAccessPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DtAccessPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DtAccessPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DtAccessPermission = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DtAccessPermission = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): DtAccessPermission = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): DtAccessPermission = where(DSL.notExists(select))
}
