/*
 * This file is generated by jOOQ.
 */
package com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.references


import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.DtAccessPermission
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.DtPlayerProfile
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.DtRole
import com.islandstudio.neon.shared.datasource.structure.schema.neon_data.tables.DtRoleAccess



/**
 * The table <code>NEON_DATA.DT_ACCESS_PERMISSION</code>.
 */
val DT_ACCESS_PERMISSION: DtAccessPermission = DtAccessPermission.DT_ACCESS_PERMISSION

/**
 * The table <code>NEON_DATA.DT_PLAYER_PROFILE</code>.
 */
val DT_PLAYER_PROFILE: DtPlayerProfile = DtPlayerProfile.DT_PLAYER_PROFILE

/**
 * The table <code>NEON_DATA.DT_ROLE</code>.
 */
val DT_ROLE: DtRole = DtRole.DT_ROLE

/**
 * The table <code>NEON_DATA.DT_ROLE_ACCESS</code>.
 */
val DT_ROLE_ACCESS: DtRoleAccess = DtRoleAccess.DT_ROLE_ACCESS
