name: Neon-Database-Extension
author: ICities
version: '1.0'
api-version: '1.17'
depend: [Neon]
main: com.islandstudio.neon.NeonDatabaseExtension
description: Database extension for Neon plugin. [Require Neon plugin in order to work.]